### ISSUE TITLE
Cannot login 

### ISSUE THREAD

**Issue by ludov04** [datacamp/Rdocumentation#24]
I have thoses errors when I try to log in

<img width="1792" alt="screen shot 2016-08-23 at 10 50 49" src="https://cloud.githubusercontent.com/assets/1741726/17885888/7cd005ce-691f-11e6-8a66-6df31afadf9a.png">

**Comment by HannesBuseyne** [comment]
think this is actually already solved. The form thing should be solved in https://github.com/datacamp/rdocumentation-app/pull/130,
The tooltip error was https://github.com/datacamp/rdocumentation-app/issues/132, and I did not get it anymore after adding the waiting for the script. Maybe it wasn't merged yet or it was cache?
do not know about the css error though

**Comment by ludov04** [comment]
I deployed dev to staging this morning. I will restart my R session and remove cache to see if it's better

**Comment by ludov04** [comment]
Still getting this when I try to log:
<img width="440" alt="screen shot 2016-08-23 at 11 44 50" src="https://cloud.githubusercontent.com/assets/1741726/17887486/0ab4dc0a-6927-11e6-9a05-c0d0925de187.png">

**Comment by ludov04** [comment]
<img width="1380" alt="screen shot 2016-08-23 at 11 45 39" src="https://cloud.githubusercontent.com/assets/1741726/17887513/241f7664-6927-11e6-906d-fffcd9bef031.png">

**Comment by HannesBuseyne** [comment]
https://github.com/datacamp/rdocumentation-app/pull/130 it's solved here, but the branch isn't merged yet, still need to solve the redirect issue with the `Accept` http-header
